---
kind: Deployment
apiVersion: apps/v1
metadata:
  - name: redis-deployment
    labels:
      name: redis
      author: vinay
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
       name: redis-pod
       labels:
         name: redis
    spec:
      containers:
        - name: myredis
          image: redis
...

