---
kind: service
apiVersion: v1
metadata:
  name: result-app-service
  labels:
    author: vinay
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
     name: result-app
...