apiVersion: apps/v1
kind: Deployment
metadata:
 - name: voting-app-deployment
   labels:
     name: voting-app
     author: vinay
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app
  spec:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app
      spec:
        containers:
          - name: votingapp
            image: dockersamples/examplevotingapp_vote
 ...


