---
kind: Deployment
apiVersion: apps/v1
metadata:
  - name: worker-app-deployment
    labels:
      name: worker-app
      author: vinay
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
...